//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird
    {
        public Bird()
        {
            this.BirdCounts = new HashSet<BirdCount>();
        }
    
        public int BirdID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BirdCount> BirdCounts { get; set; }
    }
}
